# Generated by Django 6.0.2 on 2026-02-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('empresa', models.CharField(default='001 - RN TINTAS', max_length=200, verbose_name='Empresa')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoProvisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('total_linhas', models.IntegerField(default=0, verbose_name='Total de linhas no CSV')),
                ('novos', models.IntegerField(default=0, verbose_name='Colaboradores novos')),
                ('removidos', models.IntegerField(default=0, verbose_name='Colaboradores removidos')),
                ('atualizados', models.IntegerField(default=0, verbose_name='Períodos atualizados')),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Importação de Provisão',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAquisitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_aquisitivo', models.DateField(verbose_name='Início Aquisitivo')),
                ('fim_aquisitivo', models.DateField(verbose_name='Fim Aquisitivo')),
                ('limite_ideal', models.DateField(blank=True, null=True, verbose_name='Limite Ideal')),
                ('limite_maximo', models.DateField(blank=True, null=True, verbose_name='Limite Máximo')),
                ('faltas', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Faltas')),
                ('dias_direito', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Dias Direito')),
                ('dias_gozo', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Dias Gozo')),
                ('dias_restantes', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Dias Restantes')),
                ('dias_programados', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Dias Programados')),
                ('mes_ferias', models.CharField(blank=True, help_text='Formato: YYYY-MM (ex: 2025-07)', max_length=7, null=True, verbose_name='Mês das Férias')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='provisao.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Período Aquisitivo',
                'verbose_name_plural': 'Períodos Aquisitivos',
                'ordering': ['colaborador__nome', 'inicio_aquisitivo'],
                'unique_together': {('colaborador', 'inicio_aquisitivo')},
            },
        ),
    ]
