# Generated by Django 6.0.2 on 2026-02-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodoaquisitivo',
            name='mes_ferias',
        ),
        migrations.RemoveField(
            model_name='periodoaquisitivo',
            name='observacao',
        ),
        migrations.CreateModel(
            name='ParcelaFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ferias', models.CharField(help_text='Formato YYYY-MM (ex: 2025-07)', max_length=7, verbose_name='Mês das Férias')),
                ('dias', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Dias')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='provisao.periodoaquisitivo', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Parcela de Férias',
                'verbose_name_plural': 'Parcelas de Férias',
                'ordering': ['mes_ferias'],
            },
        ),
    ]
